/*
 * Contributors:
 *    Jashar
 */
package com.hidetrace.admin.view.incominginvoice;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.stereotype.Component;

/**
 *
 * @author Jashar
 */
@Component
@EqualsAndHashCode(callSuper = false)
@Data
public class NewOutgoingInvoiceConfirmationMessagePanelView extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewOutgoingInvoiceConfirmationMessagePanelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        legalEntityLabel = new javax.swing.JLabel();
        legalEntity = new javax.swing.JLabel();
        invoiceIdLabel = new javax.swing.JLabel();
        invoiceId = new javax.swing.JLabel();
        grossWeightLabel = new javax.swing.JLabel();
        grossWeight = new javax.swing.JLabel();
        netWeightLabel = new javax.swing.JLabel();
        netWeight = new javax.swing.JLabel();
        abroadReducedLabel = new javax.swing.JLabel();
        abroadReduced = new javax.swing.JLabel();
        saltLabel = new javax.swing.JLabel();
        salt = new javax.swing.JLabel();
        certificate = new javax.swing.JLabel();
        certificateLabel = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();
        cowLabel = new javax.swing.JLabel();
        cow = new javax.swing.JLabel();
        bull = new javax.swing.JLabel();
        bullLabel = new javax.swing.JLabel();
        calf = new javax.swing.JLabel();
        calfLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        legalEntityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        legalEntityLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        legalEntityLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        legalEntityLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        legalEntity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        legalEntity.setMaximumSize(new java.awt.Dimension(200, 30));
        legalEntity.setMinimumSize(new java.awt.Dimension(200, 30));
        legalEntity.setPreferredSize(new java.awt.Dimension(200, 30));

        invoiceIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invoiceIdLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        invoiceIdLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        invoiceIdLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        invoiceId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invoiceId.setMaximumSize(new java.awt.Dimension(200, 30));
        invoiceId.setMinimumSize(new java.awt.Dimension(200, 30));
        invoiceId.setPreferredSize(new java.awt.Dimension(200, 30));

        grossWeightLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        grossWeightLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        grossWeightLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        grossWeightLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        grossWeight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        grossWeight.setMaximumSize(new java.awt.Dimension(200, 30));
        grossWeight.setMinimumSize(new java.awt.Dimension(200, 30));
        grossWeight.setPreferredSize(new java.awt.Dimension(200, 30));

        netWeightLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        netWeightLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        netWeightLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        netWeightLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        netWeight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        netWeight.setMaximumSize(new java.awt.Dimension(200, 30));
        netWeight.setMinimumSize(new java.awt.Dimension(200, 30));
        netWeight.setPreferredSize(new java.awt.Dimension(200, 30));

        abroadReducedLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        abroadReducedLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        abroadReducedLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        abroadReducedLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        abroadReduced.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        abroadReduced.setMaximumSize(new java.awt.Dimension(200, 30));
        abroadReduced.setMinimumSize(new java.awt.Dimension(200, 30));
        abroadReduced.setPreferredSize(new java.awt.Dimension(200, 30));

        saltLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saltLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        saltLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        saltLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        salt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salt.setMaximumSize(new java.awt.Dimension(200, 30));
        salt.setMinimumSize(new java.awt.Dimension(200, 30));
        salt.setPreferredSize(new java.awt.Dimension(200, 30));

        certificate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        certificate.setMaximumSize(new java.awt.Dimension(200, 30));
        certificate.setMinimumSize(new java.awt.Dimension(200, 30));
        certificate.setPreferredSize(new java.awt.Dimension(200, 30));

        certificateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        certificateLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        certificateLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        certificateLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        commentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        commentLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        commentLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        commentLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        comment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        comment.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        comment.setMaximumSize(new java.awt.Dimension(200, 200));
        comment.setMinimumSize(new java.awt.Dimension(200, 30));
        comment.setPreferredSize(new java.awt.Dimension(200, 30));

        cowLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cowLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cowLabel.setPreferredSize(new java.awt.Dimension(100, 40));

        cow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bull.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bull.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bullLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bullLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bullLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bullLabel.setPreferredSize(new java.awt.Dimension(100, 40));

        calf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        calfLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calfLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calfLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calfLabel.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Potvrdite podatke");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(legalEntityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(legalEntity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(invoiceIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(invoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(grossWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(grossWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(netWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(netWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(abroadReducedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(abroadReduced, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(certificateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(certificate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bullLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bull, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(legalEntityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(legalEntity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(invoiceIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(invoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(grossWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(grossWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(netWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(netWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(abroadReducedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(abroadReduced, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bullLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(bull, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(certificateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(certificate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(calf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abroadReduced;
    private javax.swing.JLabel abroadReducedLabel;
    private javax.swing.JLabel bull;
    private javax.swing.JLabel bullLabel;
    private javax.swing.JLabel calf;
    private javax.swing.JLabel calfLabel;
    private javax.swing.JLabel certificate;
    private javax.swing.JLabel certificateLabel;
    private javax.swing.JLabel comment;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JLabel cow;
    private javax.swing.JLabel cowLabel;
    private javax.swing.JLabel grossWeight;
    private javax.swing.JLabel grossWeightLabel;
    private javax.swing.JLabel invoiceId;
    private javax.swing.JLabel invoiceIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel legalEntity;
    private javax.swing.JLabel legalEntityLabel;
    private javax.swing.JLabel netWeight;
    private javax.swing.JLabel netWeightLabel;
    private javax.swing.JLabel salt;
    private javax.swing.JLabel saltLabel;
    // End of variables declaration//GEN-END:variables
}
