/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hidetrace.admin.view.outgoinginvoice;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.stereotype.Component;

/**
 *
 * @author Jashar
 */
@Component
@EqualsAndHashCode(callSuper = false)
@Data
public class NewOutgoingInvoiceConfirmationMessagePanelView extends javax.swing.JPanel {

    /**
     * Creates new form NewOutgoingInvoiceConfirmationMessagePanelView
     */
    public NewOutgoingInvoiceConfirmationMessagePanelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        invoiceIdLabel = new javax.swing.JLabel();
        legalEntityLabel = new javax.swing.JLabel();
        legalEntity = new javax.swing.JLabel();
        invoiceId = new javax.swing.JLabel();

        setPreferredSize(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Potvrdite podatke");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 40));

        invoiceIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invoiceIdLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        invoiceIdLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        invoiceIdLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        legalEntityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        legalEntityLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        legalEntityLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        legalEntityLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        legalEntity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        legalEntity.setMaximumSize(new java.awt.Dimension(200, 30));
        legalEntity.setMinimumSize(new java.awt.Dimension(200, 30));
        legalEntity.setPreferredSize(new java.awt.Dimension(200, 30));

        invoiceId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invoiceId.setMaximumSize(new java.awt.Dimension(200, 30));
        invoiceId.setMinimumSize(new java.awt.Dimension(200, 30));
        invoiceId.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(legalEntityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(legalEntity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(invoiceIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(invoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legalEntityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(legalEntity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invoiceId;
    private javax.swing.JLabel invoiceIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel legalEntity;
    private javax.swing.JLabel legalEntityLabel;
    // End of variables declaration//GEN-END:variables
}
