/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hidetrace.admin.view.legalentity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.stereotype.Component;

/**
 *
 * @author Jashar
 */
@Component
@EqualsAndHashCode(callSuper = false)
@Data
public class NewLegalEntityConfirmationMessagePanelView extends javax.swing.JPanel {

    /**
     * Creates new form NewLegalEntityConfirmationDialogView
     */
    public NewLegalEntityConfirmationMessagePanelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        LegalEntityNameLabel = new javax.swing.JLabel();
        LegalEntityName = new javax.swing.JLabel();
        LegalEntityAddressLabel = new javax.swing.JLabel();
        LegalEntityAddress = new javax.swing.JLabel();
        LegalEntityPhoneNumberLabel = new javax.swing.JLabel();
        LegalEntityPhoneNumber = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Potvrdite podatke");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel1, gridBagConstraints);

        LegalEntityNameLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityNameLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityNameLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(LegalEntityNameLabel, gridBagConstraints);

        LegalEntityName.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityName.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityName.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(LegalEntityName, gridBagConstraints);

        LegalEntityAddressLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddressLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddressLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(LegalEntityAddressLabel, gridBagConstraints);

        LegalEntityAddress.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddress.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddress.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(LegalEntityAddress, gridBagConstraints);

        LegalEntityPhoneNumberLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumberLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumberLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(LegalEntityPhoneNumberLabel, gridBagConstraints);

        LegalEntityPhoneNumber.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumber.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumber.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(LegalEntityPhoneNumber, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LegalEntityAddress;
    private javax.swing.JLabel LegalEntityAddressLabel;
    private javax.swing.JLabel LegalEntityName;
    private javax.swing.JLabel LegalEntityNameLabel;
    private javax.swing.JLabel LegalEntityPhoneNumber;
    private javax.swing.JLabel LegalEntityPhoneNumberLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
