/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hidetrace.admin.view.legalentity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.stereotype.Component;

/**
 *
 * @author Jashar
 */
@Component
@EqualsAndHashCode(callSuper = false)
@Data
public class NewLegalEntityConfirmationMessagePanelView extends javax.swing.JPanel {

    /**
     * Creates new form NewLegalEntityConfirmationDialogView
     */
    public NewLegalEntityConfirmationMessagePanelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LegalEntityNameLabel = new javax.swing.JLabel();
        LegalEntityName = new javax.swing.JLabel();
        LegalEntityAddressLabel = new javax.swing.JLabel();
        LegalEntityAddress = new javax.swing.JLabel();
        LegalEntityPhoneNumberLabel = new javax.swing.JLabel();
        LegalEntityPhoneNumber = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Potvrdite podatke");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 40));

        LegalEntityNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LegalEntityNameLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityNameLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityNameLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        LegalEntityName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LegalEntityName.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityName.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityName.setPreferredSize(new java.awt.Dimension(200, 30));

        LegalEntityAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LegalEntityAddressLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddressLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddressLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        LegalEntityAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LegalEntityAddress.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddress.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityAddress.setPreferredSize(new java.awt.Dimension(200, 30));

        LegalEntityPhoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LegalEntityPhoneNumberLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumberLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumberLabel.setPreferredSize(new java.awt.Dimension(200, 30));

        LegalEntityPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LegalEntityPhoneNumber.setMaximumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumber.setMinimumSize(new java.awt.Dimension(200, 30));
        LegalEntityPhoneNumber.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LegalEntityNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(LegalEntityName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LegalEntityAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(LegalEntityAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LegalEntityPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(LegalEntityPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LegalEntityNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LegalEntityName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LegalEntityAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LegalEntityAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LegalEntityPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LegalEntityPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LegalEntityAddress;
    private javax.swing.JLabel LegalEntityAddressLabel;
    private javax.swing.JLabel LegalEntityName;
    private javax.swing.JLabel LegalEntityNameLabel;
    private javax.swing.JLabel LegalEntityPhoneNumber;
    private javax.swing.JLabel LegalEntityPhoneNumberLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
